CREATE OR REPLACE TABLE Healthcare_DB.RAW_SCHEMA.FACILITIES(
    "Facility ID" VARCHAR,
    "Facility Name" VARCHAR,
    "Address" VARCHAR,
    "City/Town" VARCHAR,
    "State" VARCHAR,
    "ZIP Code" VARCHAR,
    "County/Parish" VARCHAR,
    "Telephone Number" VARCHAR,
    "Hospital Type" VARCHAR,
    "Hospital Ownership" VARCHAR,
    "Emergency Services" VARCHAR,
    "Meets criteria for birthing friendly designation" VARCHAR,
    "Hospital overall rating" VARCHAR,
    "Hospital overall rating footnote" VARCHAR,
    "MORT Group Measure Count" VARCHAR,
    "Count of Facility MORT Measures" VARCHAR,
    "Count of MORT Measures Better" VARCHAR,
    "Count of MORT Measures No Different" VARCHAR,
    "Count of MORT Measures Worse" VARCHAR,
    "MORT Group Footnote" VARCHAR,
    "Safety Group Measure Count" VARCHAR,
    "Count of Facility Safety Measures" VARCHAR,
    "Count of Safety Measures Better" VARCHAR,
    "Count of Safety Measures No Different" VARCHAR,
    "Count of Safety Measures Worse" VARCHAR,
    "Safety Group Footnote" VARCHAR,
    "READM Group Measure Count" VARCHAR,
    "Count of Facility READM Measures" VARCHAR,
    "Count of READM Measures Better" VARCHAR,
    "Count of READM Measures No Different" VARCHAR,
    "Count of READM Measures Worse" VARCHAR,
    "READM Group Footnote" VARCHAR,
    "Pt Exp Group Measure Count" VARCHAR,
    "Count of Facility Pt Exp Measures" VARCHAR,
    "Pt Exp Group Footnote" VARCHAR,
    "TE Group Measure Count" VARCHAR,
    "Count of Facility TE Measures" VARCHAR,
    "TE Group Footnote" VARCHAR
);
    
    CREATE OR REPLACE TABLE Healthcare_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL (
    "Facility ID" VARCHAR,
    "Facility Name" VARCHAR,
    "Address" VARCHAR,
    "City/Town" VARCHAR,
    "State" VARCHAR,
    "ZIP Code" VARCHAR,
    "County/Parish" VARCHAR,
    "Telephone Number" VARCHAR,
    "Measure ID" VARCHAR,
    "Measure Name" VARCHAR,
    "Compared to National" VARCHAR,
    "Denominator" VARCHAR,
    "Score" VARCHAR,
    "Lower Estimate" VARCHAR,
    "Higher Estimate" VARCHAR,
    "Footnote" VARCHAR,
    "Start Date" DATE,
    "End Date" DATE
);

CREATE OR REPLACE TABLE Healthcare_DB.RAW_SCHEMA.READMISSION_METRICS(
    "Facility Name" VARCHAR,
    "Facility ID" VARCHAR,
    "State" VARCHAR,
    "Measure Name" VARCHAR,
    "Number of Discharges" FLOAT,
    "Footnote" FLOAT,
    "Excess Readmission Ratio" FLOAT,
    "Predicted Readmission Rate" FLOAT,
    "Expected Readmission Rate" FLOAT,
    "Number of Readmissions" VARCHAR,
    "Start Date" DATE,
    "End Date" DATE
);

CREATE OR REPLACE TABLE HEALTHCARE_DB.RAW_SCHEMA.COST_ANALYTICS(
    "Facility ID" VARCHAR,
    "Measure ID" VARCHAR,
    "Value" FLOAT,
    "Footnote" FLOAT,
    "Start Date" DATE,
    "End Date" DATE
);

CREATE OR REPLACE TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS (
    "Facility ID" VARCHAR,
    "Facility Name" VARCHAR,
    "Address" VARCHAR,
    "City/Town" VARCHAR,
    "State" VARCHAR,
    "ZIP Code" VARCHAR,
    "County/Parish" VARCHAR,
    "Telephone Number" VARCHAR,
    "Condition" VARCHAR,
    "Measure ID" VARCHAR,
    "Measure Name" VARCHAR,
    "Score" VARCHAR,
    "Sample" VARCHAR,
    "Footnote" VARCHAR,
    "Start Date" DATE,
    "End Date" DATE
);

CREATE OR REPLACE TABLE Healthcare_DB.RAW_SCHEMA.PATIENT_SURVEY (
    "Facility ID" VARCHAR(10),
    "Facility Name" VARCHAR(255),
    "Address" VARCHAR(255),
    "City" VARCHAR(100),
    "State" VARCHAR(2),
    "ZIP Code" VARCHAR(10),
    "County Name" VARCHAR(100),
    "Telephone Number" VARCHAR(20),
    "HCAHPS Measure ID" VARCHAR(100),
    "HCAHPS Question" VARCHAR(1000),
    "HCAHPS Answer Description" VARCHAR(1000),
    "Patient Survey Star Rating" VARCHAR(50),
    "Patient Survey Star Rating Footnote" VARCHAR(1000),
    "HCAHPS Answer Percent" VARCHAR(50),
    "HCAHPS Answer Percent Footnote" VARCHAR(1000),
    "HCAHPS Linear Mean Value" VARCHAR(50),
    "Number of Completed Surveys" VARCHAR(50),
    "Number of Completed Surveys Footnote" VARCHAR(1000),
    "Survey Response Rate Percent" VARCHAR(50),
    "Survey Response Rate Percent Footnote" VARCHAR(1000),
    "Start Date" DATE,
    "End Date" DATE
);