----------------------------------------------------------------------
-- ANALYTICS LAYER 1: HOSPITAL PAYER SCORECARD
-- Unified per-hospital scorecard joining all transformed tables
-- for payer network evaluation and contract negotiation
----------------------------------------------------------------------
USE ROLE DATA_ANALYST_ROLE;
USE WAREHOUSE DATA_ANALYTICS_WH;

CREATE OR REPLACE TABLE HEALTHCARE_DB.ANALYTICS_SCHEMA.ANALYTICS_HOSPITAL_PAYER_SCORECARD AS
WITH readmission_summary AS (
    SELECT
        FACILITY_ID,
        COUNT(*)                                                        AS TOTAL_CONDITIONS_MEASURED,
        SUM(NUMBER_OF_DISCHARGES)                                       AS TOTAL_DISCHARGES,
        SUM(NUMBER_OF_READMISSIONS)                                     AS TOTAL_READMISSIONS,
        ROUND(AVG(EXCESS_READMISSION_RATIO), 4)                        AS AVG_EXCESS_READMISSION_RATIO,
        SUM(ESTIMATED_EXCESS_READMISSIONS)                              AS TOTAL_ESTIMATED_EXCESS_READMISSIONS,
        COUNT(CASE WHEN PENALTY_STATUS = 'Penalized (Above Expected)' THEN 1 END) AS CONDITIONS_PENALIZED,
        MAX(PAYER_RISK_TIER)                                            AS WORST_READMISSION_RISK_TIER
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_READMISSION_METRICS
    GROUP BY FACILITY_ID
),
complication_summary AS (
    SELECT
        FACILITY_ID,
        COUNT(CASE WHEN PAYER_RISK_CLASSIFICATION = 'High Risk' THEN 1 END)   AS HIGH_RISK_MEASURES,
        COUNT(CASE WHEN PAYER_RISK_CLASSIFICATION = 'Low Risk' THEN 1 END)    AS LOW_RISK_MEASURES,
        COUNT(CASE WHEN MEASURE_CATEGORY = 'Mortality' THEN 1 END)            AS MORTALITY_MEASURES,
        COUNT(CASE WHEN MEASURE_CATEGORY = 'Patient Safety' THEN 1 END)       AS SAFETY_MEASURES,
        ROUND(AVG(CASE WHEN MEASURE_CATEGORY = 'Mortality' THEN SCORE END), 2) AS AVG_MORTALITY_SCORE,
        ROUND(AVG(CASE WHEN MEASURE_CATEGORY = 'Patient Safety' THEN SCORE END), 2) AS AVG_SAFETY_SCORE
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_COMPLICATIONS_AND_DEATHS
    WHERE SCORE IS NOT NULL
    GROUP BY FACILITY_ID
),
survey_summary AS (
    SELECT
        FACILITY_ID,
        MAX(CASE WHEN MEASURE_ID = 'H_HSP_RATING_STAR_RATING' THEN STAR_RATING END)    AS OVERALL_STAR_RATING,
        MAX(CASE WHEN MEASURE_ID = 'H_HSP_RATING_9_10' THEN ANSWER_PERCENT END)        AS PCT_RATING_9_OR_10,
        MAX(CASE WHEN MEASURE_ID = 'H_RECMND_DY' THEN ANSWER_PERCENT END)              AS PCT_WOULD_RECOMMEND,
        MAX(CASE WHEN MEASURE_ID = 'H_RECMND_DN' THEN ANSWER_PERCENT END)              AS PCT_WOULD_NOT_RECOMMEND,
        MAX(COMPLETED_SURVEYS)                                                           AS COMPLETED_SURVEYS,
        MAX(RESPONSE_RATE_PCT)                                                           AS SURVEY_RESPONSE_RATE
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_PATIENT_SURVEY
    GROUP BY FACILITY_ID
)
SELECT
    f.FACILITY_ID,
    f.FACILITY_NAME,
    f.CITY,
    f.STATE,
    f.ZIP_CODE,
    f.COUNTY,
    f.HOSPITAL_TYPE,
    f.HOSPITAL_OWNERSHIP,
    f.OVERALL_RATING,
    f.PAYER_NETWORK_TIER,
    f.READMISSION_RISK_FLAG,
    f.QUALITY_CONCERN_LEVEL,

    r.TOTAL_CONDITIONS_MEASURED,
    r.TOTAL_DISCHARGES,
    r.TOTAL_READMISSIONS,
    r.AVG_EXCESS_READMISSION_RATIO,
    r.TOTAL_ESTIMATED_EXCESS_READMISSIONS,
    r.CONDITIONS_PENALIZED,

    c.SPENDING_RATIO                                                    AS MSPB_SPENDING_RATIO,
    c.COST_EFFICIENCY_TIER,
    c.SPENDING_DEVIATION_PCT,

    cd.HIGH_RISK_MEASURES                                               AS COMPLICATION_HIGH_RISK_COUNT,
    cd.LOW_RISK_MEASURES                                                AS COMPLICATION_LOW_RISK_COUNT,
    cd.AVG_MORTALITY_SCORE,
    cd.AVG_SAFETY_SCORE,

    s.OVERALL_STAR_RATING                                               AS PATIENT_EXPERIENCE_STAR,
    s.PCT_WOULD_RECOMMEND,
    s.PCT_WOULD_NOT_RECOMMEND,
    s.COMPLETED_SURVEYS,

    CASE
        WHEN f.PAYER_NETWORK_TIER = 'Preferred'
             AND COALESCE(c.SPENDING_RATIO, 1) <= 1.0
             AND COALESCE(r.AVG_EXCESS_READMISSION_RATIO, 1) <= 1.0    THEN 'Top Performer'
        WHEN f.PAYER_NETWORK_TIER = 'High Risk'
             OR COALESCE(c.SPENDING_RATIO, 1) >= 1.10
             OR COALESCE(r.CONDITIONS_PENALIZED, 0) >= 3               THEN 'Under Review'
        WHEN f.QUALITY_CONCERN_LEVEL = 'High'
             OR COALESCE(cd.HIGH_RISK_MEASURES, 0) >= 3                 THEN 'Watch List'
        ELSE 'Standard'
    END                                                                 AS PAYER_COMPOSITE_STATUS,

    ROUND(
        (COALESCE(f.OVERALL_RATING, 0) * 20.0)
        + (CASE WHEN COALESCE(r.AVG_EXCESS_READMISSION_RATIO, 1) <= 1.0 THEN 25 ELSE GREATEST(0, 25 - ((r.AVG_EXCESS_READMISSION_RATIO - 1.0) * 250)) END)
        + (CASE WHEN COALESCE(c.SPENDING_RATIO, 1) <= 1.0 THEN 25 ELSE GREATEST(0, 25 - ((c.SPENDING_RATIO - 1.0) * 250)) END)
        + (COALESCE(s.OVERALL_STAR_RATING, 0) * 6.0)
    , 2)                                                                AS PAYER_COMPOSITE_SCORE

FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_FACILITIES f
LEFT JOIN readmission_summary r       ON f.FACILITY_ID = r.FACILITY_ID
LEFT JOIN HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_COST_ANALYTICS c ON f.FACILITY_ID = c.FACILITY_ID
LEFT JOIN complication_summary cd      ON f.FACILITY_ID = cd.FACILITY_ID
LEFT JOIN survey_summary s             ON f.FACILITY_ID = s.FACILITY_ID;
