----------------------------------------------------------------------
-- ANALYTICS LAYER 3: COST VS QUALITY CORRELATION
-- Links Medicare spending efficiency with safety, mortality,
-- and readmission outcomes for payer value-based contracting
----------------------------------------------------------------------
CREATE OR REPLACE TABLE HEALTHCARE_DB.ANALYTICS_SCHEMA.ANALYTICS_COST_VS_QUALITY AS
WITH readmission_agg AS (
    SELECT
        FACILITY_ID,
        ROUND(AVG(EXCESS_READMISSION_RATIO), 4)                        AS AVG_EXCESS_READMISSION_RATIO,
        SUM(ESTIMATED_EXCESS_READMISSIONS)                              AS TOTAL_EXCESS_READMISSIONS,
        COUNT(CASE WHEN PENALTY_STATUS = 'Penalized (Above Expected)' THEN 1 END) AS CONDITIONS_PENALIZED
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_READMISSION_METRICS
    GROUP BY FACILITY_ID
),
complication_agg AS (
    SELECT
        FACILITY_ID,
        COUNT(CASE WHEN PAYER_RISK_CLASSIFICATION = 'High Risk' THEN 1 END) AS HIGH_RISK_MEASURES,
        COUNT(CASE WHEN PAYER_RISK_CLASSIFICATION = 'Low Risk' THEN 1 END)  AS LOW_RISK_MEASURES,
        ROUND(AVG(CASE WHEN MEASURE_CATEGORY = 'Mortality' THEN SCORE END), 2)       AS AVG_MORTALITY_RATE,
        ROUND(AVG(CASE WHEN MEASURE_CATEGORY = 'Patient Safety' THEN SCORE END), 2)  AS AVG_SAFETY_EVENT_RATE
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_COMPLICATIONS_AND_DEATHS
    WHERE SCORE IS NOT NULL
    GROUP BY FACILITY_ID
)
SELECT
    f.FACILITY_ID,
    f.FACILITY_NAME,
    f.STATE,
    f.HOSPITAL_TYPE,
    f.HOSPITAL_OWNERSHIP,
    f.OVERALL_RATING,
    f.PAYER_NETWORK_TIER,

    c.SPENDING_RATIO                                                    AS MSPB_SPENDING_RATIO,
    c.COST_EFFICIENCY_TIER,
    c.SPENDING_DEVIATION_PCT,

    r.AVG_EXCESS_READMISSION_RATIO,
    r.TOTAL_EXCESS_READMISSIONS,
    r.CONDITIONS_PENALIZED,

    cd.AVG_MORTALITY_RATE,
    cd.AVG_SAFETY_EVENT_RATE,
    cd.HIGH_RISK_MEASURES,
    cd.LOW_RISK_MEASURES,

    CASE
        WHEN COALESCE(c.SPENDING_RATIO, 1) <= 1.0
             AND COALESCE(r.AVG_EXCESS_READMISSION_RATIO, 1) <= 1.0
             AND COALESCE(cd.HIGH_RISK_MEASURES, 0) = 0                 THEN 'High Value'
        WHEN COALESCE(c.SPENDING_RATIO, 1) <= 1.0
             AND (COALESCE(r.AVG_EXCESS_READMISSION_RATIO, 1) > 1.0
                  OR COALESCE(cd.HIGH_RISK_MEASURES, 0) > 0)           THEN 'Low Cost / Quality Gap'
        WHEN COALESCE(c.SPENDING_RATIO, 1) > 1.0
             AND COALESCE(r.AVG_EXCESS_READMISSION_RATIO, 1) <= 1.0
             AND COALESCE(cd.HIGH_RISK_MEASURES, 0) = 0                 THEN 'High Cost / Good Quality'
        WHEN COALESCE(c.SPENDING_RATIO, 1) > 1.0
             AND (COALESCE(r.AVG_EXCESS_READMISSION_RATIO, 1) > 1.0
                  OR COALESCE(cd.HIGH_RISK_MEASURES, 0) >= 2)          THEN 'Low Value'
        ELSE 'Moderate Value'
    END                                                                 AS PAYER_VALUE_QUADRANT,

    NTILE(10) OVER (ORDER BY COALESCE(c.SPENDING_RATIO, 1) ASC)        AS COST_DECILE,
    NTILE(10) OVER (ORDER BY COALESCE(r.AVG_EXCESS_READMISSION_RATIO, 1) ASC) AS READMISSION_DECILE

FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_FACILITIES f
LEFT JOIN HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_COST_ANALYTICS c  ON f.FACILITY_ID = c.FACILITY_ID
LEFT JOIN readmission_agg r                                       ON f.FACILITY_ID = r.FACILITY_ID
LEFT JOIN complication_agg cd                                     ON f.FACILITY_ID = cd.FACILITY_ID;
