----------------------------------------------------------------------
-- ANALYTICS LAYER 4: STATE-LEVEL PAYER BENCHMARKING
-- Aggregated state-level view for regional payer strategy,
-- network adequacy planning, and geographic risk assessment
----------------------------------------------------------------------
CREATE OR REPLACE TABLE HEALTHCARE_DB.ANALYTICS_SCHEMA.ANALYTICS_STATE_BENCHMARKING AS
WITH state_readmission AS (
    SELECT
        STATE,
        ROUND(AVG(EXCESS_READMISSION_RATIO), 4)                        AS AVG_EXCESS_READMISSION_RATIO,
        SUM(NUMBER_OF_DISCHARGES)                                       AS TOTAL_DISCHARGES,
        SUM(NUMBER_OF_READMISSIONS)                                     AS TOTAL_READMISSIONS,
        SUM(ESTIMATED_EXCESS_READMISSIONS)                              AS TOTAL_EXCESS_READMISSIONS,
        COUNT(DISTINCT FACILITY_ID)                                     AS HOSPITALS_WITH_READMISSION_DATA,
        COUNT(DISTINCT CASE WHEN PENALTY_STATUS = 'Penalized (Above Expected)' THEN FACILITY_ID END) AS HOSPITALS_PENALIZED
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_READMISSION_METRICS
    GROUP BY STATE
),
state_cost AS (
    SELECT
        f.STATE,
        ROUND(AVG(c.SPENDING_RATIO), 4)                                AS AVG_SPENDING_RATIO,
        COUNT(CASE WHEN c.COST_EFFICIENCY_TIER IN ('High Overspend','Moderate Overspend') THEN 1 END) AS HOSPITALS_OVERSPENDING,
        COUNT(CASE WHEN c.COST_EFFICIENCY_TIER IN ('Efficient','Highly Efficient') THEN 1 END)        AS HOSPITALS_EFFICIENT
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_COST_ANALYTICS c
    JOIN HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_FACILITIES f ON c.FACILITY_ID = f.FACILITY_ID
    GROUP BY f.STATE
),
state_complications AS (
    SELECT
        STATE,
        COUNT(DISTINCT FACILITY_ID)                                     AS HOSPITALS_WITH_COMPLICATION_DATA,
        COUNT(CASE WHEN PAYER_RISK_CLASSIFICATION = 'High Risk' THEN 1 END) AS TOTAL_HIGH_RISK_MEASURES,
        COUNT(CASE WHEN PAYER_RISK_CLASSIFICATION = 'Low Risk' THEN 1 END)  AS TOTAL_LOW_RISK_MEASURES,
        ROUND(AVG(CASE WHEN MEASURE_CATEGORY = 'Mortality' THEN SCORE END), 2) AS AVG_MORTALITY_RATE,
        ROUND(AVG(CASE WHEN MEASURE_CATEGORY = 'Patient Safety' THEN SCORE END), 2) AS AVG_SAFETY_EVENT_RATE
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_COMPLICATIONS_AND_DEATHS
    WHERE SCORE IS NOT NULL
    GROUP BY STATE
),
state_survey AS (
    SELECT
        STATE,
        ROUND(AVG(CASE WHEN MEASURE_ID = 'H_HSP_RATING_STAR_RATING' THEN STAR_RATING END), 2) AS AVG_PATIENT_STAR_RATING,
        ROUND(AVG(RESPONSE_RATE_PCT), 2)                                AS AVG_SURVEY_RESPONSE_RATE
    FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_PATIENT_SURVEY
    GROUP BY STATE
)
SELECT
    f.STATE,
    COUNT(DISTINCT f.FACILITY_ID)                                       AS TOTAL_HOSPITALS,
    COUNT(DISTINCT CASE WHEN f.PAYER_NETWORK_TIER = 'Preferred' THEN f.FACILITY_ID END)  AS PREFERRED_TIER_HOSPITALS,
    COUNT(DISTINCT CASE WHEN f.PAYER_NETWORK_TIER = 'Standard' THEN f.FACILITY_ID END)   AS STANDARD_TIER_HOSPITALS,
    COUNT(DISTINCT CASE WHEN f.PAYER_NETWORK_TIER = 'High Risk' THEN f.FACILITY_ID END)  AS HIGH_RISK_TIER_HOSPITALS,
    COUNT(DISTINCT CASE WHEN f.PAYER_NETWORK_TIER = 'Unrated' THEN f.FACILITY_ID END)    AS UNRATED_HOSPITALS,
    ROUND(AVG(f.OVERALL_RATING), 2)                                     AS AVG_OVERALL_RATING,

    sr.AVG_EXCESS_READMISSION_RATIO,
    sr.TOTAL_DISCHARGES,
    sr.TOTAL_READMISSIONS,
    sr.TOTAL_EXCESS_READMISSIONS,
    sr.HOSPITALS_PENALIZED,
    ROUND(sr.HOSPITALS_PENALIZED * 100.0 / NULLIF(sr.HOSPITALS_WITH_READMISSION_DATA, 0), 2) AS PCT_HOSPITALS_PENALIZED,

    sc.AVG_SPENDING_RATIO,
    sc.HOSPITALS_OVERSPENDING,
    sc.HOSPITALS_EFFICIENT,

    scd.AVG_MORTALITY_RATE,
    scd.AVG_SAFETY_EVENT_RATE,
    scd.TOTAL_HIGH_RISK_MEASURES,

    ss.AVG_PATIENT_STAR_RATING,
    ss.AVG_SURVEY_RESPONSE_RATE,

    RANK() OVER (ORDER BY COALESCE(sr.AVG_EXCESS_READMISSION_RATIO, 999) ASC) AS STATE_READMISSION_RANK,
    RANK() OVER (ORDER BY COALESCE(sc.AVG_SPENDING_RATIO, 999) ASC)            AS STATE_COST_RANK

FROM HEALTHCARE_DB.TRANSFORM_SCHEMA.TRANSFORMED_FACILITIES f
LEFT JOIN state_readmission sr       ON f.STATE = sr.STATE
LEFT JOIN state_cost sc              ON f.STATE = sc.STATE
LEFT JOIN state_complications scd    ON f.STATE = scd.STATE
LEFT JOIN state_survey ss            ON f.STATE = ss.STATE
GROUP BY
    f.STATE,
    sr.AVG_EXCESS_READMISSION_RATIO, sr.TOTAL_DISCHARGES, sr.TOTAL_READMISSIONS,
    sr.TOTAL_EXCESS_READMISSIONS, sr.HOSPITALS_PENALIZED, sr.HOSPITALS_WITH_READMISSION_DATA,
    sc.AVG_SPENDING_RATIO, sc.HOSPITALS_OVERSPENDING, sc.HOSPITALS_EFFICIENT,
    scd.AVG_MORTALITY_RATE, scd.AVG_SAFETY_EVENT_RATE, scd.TOTAL_HIGH_RISK_MEASURES,
    ss.AVG_PATIENT_STAR_RATING, ss.AVG_SURVEY_RESPONSE_RATE;
