--SETTING UP ALERTS

-- Prerequisites: Grant alert privileges to admin role
GRANT EXECUTE ALERT ON ACCOUNT TO ROLE ADMIN_ROLE;
GRANT EXECUTE MANAGED ALERT ON ACCOUNT TO ROLE ADMIN_ROLE;

-- Create alert history logging table
CREATE OR REPLACE TABLE Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_LOG(
alert_name STRING,
alert_time TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
alert_message STRING
);

--COST USAGE ALERTS
-- 1. Daily Credit Threshold Alert (>20 credits/day)
CREATE OR REPLACE ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_DAILY_CREDIT_THRESHOLD
SCHEDULE='1440 MINUTE'
IF (EXISTS(
SELECT 1
FROM Healthcare_DB.GOVERNANCE_SCHEMA.V_DAILY_CREDIT_TREND
WHERE usage_date=CURRENT_DATE()-1
AND daily_credits>20
))
THEN
INSERT INTO Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_LOG
SELECT 'DAILY_CREDIT_THRESHOLD',
'Daily credit usage exceeded 20 credits';

-- 2. Warehouse Credit Spike Alert (single warehouse >5 credits/hour)
CREATE OR REPLACE ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_WAREHOUSE_CREDIT_SPIKE
SCHEDULE='60 MINUTE'
IF (EXISTS(
SELECT 1
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE start_time>=DATEADD(HOUR,-1,CURRENT_TIMESTAMP())
GROUP BY warehouse_name
HAVING SUM(credits_used)>5
))
THEN
INSERT INTO Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_LOG
SELECT 'WAREHOUSE_CREDIT_SPIKE',
'Warehouse exceeded 5 credits in last hour';

-- 3. Weekly Cost Increase Alert (>25% increase WoW)
CREATE OR REPLACE ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_WEEKLY_COST_INCREASE
SCHEDULE='USING CRON 0 8 * * 1 America/New_York'
IF (EXISTS(
SELECT 1
FROM Healthcare_DB.GOVERNANCE_SCHEMA.V_WEEK_OVER_WEEK_COMPARISON
QUALIFY
MAX(CASE WHEN period='current_week' THEN total_credits END)
>
MAX(CASE WHEN period='previous_week' THEN total_credits END)*1.25
))
THEN
INSERT INTO Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_LOG
SELECT 'WEEKLY_COST_INCREASE',
'Weekly credit usage increased by more than 25%';

-- 4. Expensive Query Alert (query >0.5 credits)
CREATE OR REPLACE ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_EXPENSIVE_QUERY
SCHEDULE='30 MINUTE'
IF (EXISTS(
SELECT 1
FROM Healthcare_DB.GOVERNANCE_SCHEMA.V_TOP_EXPENSIVE_QUERIES
WHERE credits_used>0.5
AND start_time>=DATEADD(MINUTE,-30,CURRENT_TIMESTAMP())
))
THEN
INSERT INTO Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_LOG
SELECT 'EXPENSIVE_QUERY',
'Query consumed more than 0.5 credits';

-- =============================================================================
-- RESUME ALL ALERTS
-- =============================================================================

ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_DAILY_CREDIT_THRESHOLD RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_WAREHOUSE_CREDIT_SPIKE RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_WEEKLY_COST_INCREASE RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_EXPENSIVE_QUERY RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_STORAGE_GROWTH RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_RESOURCE_MONITOR_WARNING RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_LONG_RUNNING_QUERY RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_QUERY_QUEUE_TIME RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_FAILED_QUERIES RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_WAREHOUSE_IDLE RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_HIGH_CONCURRENCY RESUME;
ALTER ALERT Healthcare_DB.GOVERNANCE_SCHEMA.ALERT_DATA_TRANSFER_SPIKE RESUME;

-- Verification
SHOW ALERTS IN SCHEMA Healthcare_DB.GOVERNANCE_SCHEMA;