----------------------------------------------------------------------
-- HEALTHCARE DATA GOVERNANCE
-- Tags, Masking Policies & Row Access Policy for RAW_SCHEMA tables
-- Applies to: FACILITIES, PATIENT_SURVEY, ENCOUNTERS,
--             COMPLICATIONS_AND_DEATHS_HOSPITAL, READMISSION_METRICS,
--             COST_ANALYTICS
----------------------------------------------------------------------

----------------------------------------------------------------------
-- 1. GOVERNANCE SCHEMA
----------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.GOVERNANCE
    COMMENT = 'Centralized schema for tags, masking policies, and access policies';

----------------------------------------------------------------------
-- 2. OBJECT TAGS
----------------------------------------------------------------------

CREATE OR REPLACE TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION
    ALLOWED_VALUES 'PII', 'PHI', 'SENSITIVE', 'INTERNAL', 'PUBLIC'
    COMMENT = 'Data sensitivity classification per HIPAA/compliance requirements';

CREATE OR REPLACE TAG HEALTHCARE_DB.GOVERNANCE.DATA_DOMAIN
    ALLOWED_VALUES 'FACILITY_IDENTITY', 'CONTACT_INFO', 'LOCATION', 'CLINICAL_METRIC', 'FINANCIAL', 'SURVEY', 'OPERATIONAL'
    COMMENT = 'Business domain of the data element';

CREATE OR REPLACE TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE
    ALLOWED_VALUES 'FACILITY_NAME', 'ADDRESS', 'PHONE', 'ZIP_CODE', 'NONE'
    COMMENT = 'Type of Personally/Facility Identifiable Information';

----------------------------------------------------------------------
-- 3. APPLY TAGS TO RAW_SCHEMA TABLE COLUMNS
----------------------------------------------------------------------

-- FACILITIES
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN
    "Facility Name" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                        TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'FACILITY_NAME';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN
    "Address" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                  TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ADDRESS';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN
    "Telephone Number" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                           TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'PHONE';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN
    "ZIP Code" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE',
                   TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ZIP_CODE';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN
    "Hospital overall rating" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'INTERNAL',
                                  TAG HEALTHCARE_DB.GOVERNANCE.DATA_DOMAIN = 'CLINICAL_METRIC';

-- PATIENT_SURVEY
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN
    "Facility Name" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                        TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'FACILITY_NAME';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN
    "Address" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                  TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ADDRESS';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN
    "Telephone Number" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                           TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'PHONE';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN
    "ZIP Code" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE',
                   TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ZIP_CODE';

-- ENCOUNTERS
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN
    "Facility Name" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                        TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'FACILITY_NAME';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN
    "Address" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                  TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ADDRESS';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN
    "Telephone Number" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                           TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'PHONE';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN
    "ZIP Code" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE',
                   TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ZIP_CODE';

-- COMPLICATIONS_AND_DEATHS_HOSPITAL
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN
    "Facility Name" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                        TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'FACILITY_NAME';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN
    "Address" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                  TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ADDRESS';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN
    "Telephone Number" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                           TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'PHONE';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN
    "ZIP Code" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE',
                   TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'ZIP_CODE';

-- READMISSION_METRICS
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.READMISSION_METRICS MODIFY COLUMN
    "Facility Name" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'PII',
                        TAG HEALTHCARE_DB.GOVERNANCE.PII_TYPE = 'FACILITY_NAME';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.READMISSION_METRICS MODIFY COLUMN
    "Number of Readmissions" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE',
                                 TAG HEALTHCARE_DB.GOVERNANCE.DATA_DOMAIN = 'CLINICAL_METRIC';
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.READMISSION_METRICS MODIFY COLUMN
    "Excess Readmission Ratio" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'INTERNAL',
                                   TAG HEALTHCARE_DB.GOVERNANCE.DATA_DOMAIN = 'CLINICAL_METRIC';

-- COST_ANALYTICS
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COST_ANALYTICS MODIFY COLUMN
    "Value" SET TAG HEALTHCARE_DB.GOVERNANCE.DATA_CLASSIFICATION = 'SENSITIVE',
                TAG HEALTHCARE_DB.GOVERNANCE.DATA_DOMAIN = 'FINANCIAL';

----------------------------------------------------------------------
-- VERIFICATION QUERIES
---------------------------------------------------------------------

-- Check all tags applied
-- SELECT *
-- FROM TABLE(HEALTHCARE_DB.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
--     'HEALTHCARE_DB.RAW_SCHEMA.FACILITIES', 'TABLE'
-- ));


----------------------------------------------------------------------
-- 1. SHARED UNMASK FUNCTION (Split Pattern)
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION HEALTHCARE_DB.GOVERNANCE.UNMASK_PII()
RETURNS BOOLEAN
MEMOIZABLE
AS
$$
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'ADMIN_ROLE', 'DATA_ENGINEER_ROLE')
$$;

CREATE OR REPLACE FUNCTION HEALTHCARE_DB.GOVERNANCE.UNMASK_SENSITIVE()
RETURNS BOOLEAN
MEMOIZABLE
AS
$$
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'ADMIN_ROLE', 'DATA_ENGINEER_ROLE', 'DATA_ANALYST_ROLE')
$$;

----------------------------------------------------------------------
-- 2. MASKING POLICIES
----------------------------------------------------------------------

CREATE OR REPLACE MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII
AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN HEALTHCARE_DB.GOVERNANCE.UNMASK_PII() THEN val
        ELSE '***MASKED***'
    END
COMMENT = 'Masks string PII (names, addresses). Full access: ACCOUNTADMIN, ADMIN_ROLE, DATA_ENGINEER_ROLE.';

CREATE OR REPLACE MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_PHONE
AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN HEALTHCARE_DB.GOVERNANCE.UNMASK_PII() THEN val
        ELSE CONCAT('***-***-', RIGHT(val, 4))
    END
COMMENT = 'Partially masks phone numbers showing last 4 digits.';

CREATE OR REPLACE MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_ZIP_CODE
AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN HEALTHCARE_DB.GOVERNANCE.UNMASK_SENSITIVE() THEN val
        ELSE LEFT(val, 3) || '**'
    END
COMMENT = 'Masks ZIP code to 3-digit prefix for geographic generalization.';

CREATE OR REPLACE MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_FINANCIAL_VALUE
AS (val FLOAT)
RETURNS FLOAT ->
    CASE
        WHEN HEALTHCARE_DB.GOVERNANCE.UNMASK_SENSITIVE() THEN val
        ELSE NULL
    END
COMMENT = 'Masks financial metric values. Returns NULL for unauthorized roles.';

CREATE OR REPLACE MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_CLINICAL_METRIC
AS (val FLOAT)
RETURNS FLOAT ->
    CASE
        WHEN HEALTHCARE_DB.GOVERNANCE.UNMASK_SENSITIVE() THEN val
        ELSE ROUND(val, 0)
    END
COMMENT = 'Reduces precision of clinical metrics for unauthorized roles.';

CREATE OR REPLACE MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_CLINICAL_METRIC_VARCHAR
AS (val VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN HEALTHCARE_DB.GOVERNANCE.UNMASK_SENSITIVE() THEN val
        ELSE '***'
    END
COMMENT = 'Masks varchar clinical metrics for unauthorized roles.';

----------------------------------------------------------------------
-- 3. APPLY MASKING POLICIES TO COLUMNS
----------------------------------------------------------------------

-- FACILITIES
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN "Facility Name"    SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN "Address"           SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN "Telephone Number"  SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_PHONE;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES MODIFY COLUMN "ZIP Code"          SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_ZIP_CODE;

-- PATIENT_SURVEY
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN "Facility Name"    SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN "Address"           SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN "Telephone Number"  SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_PHONE;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY MODIFY COLUMN "ZIP Code"          SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_ZIP_CODE;

-- ENCOUNTERS
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN "Facility Name"    SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN "Address"           SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN "Telephone Number"  SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_PHONE;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS MODIFY COLUMN "ZIP Code"          SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_ZIP_CODE;

-- COMPLICATIONS_AND_DEATHS_HOSPITAL
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN "Facility Name"    SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN "Address"           SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN "Telephone Number"  SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_PHONE;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL MODIFY COLUMN "ZIP Code"          SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_ZIP_CODE;

-- READMISSION_METRICS
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.READMISSION_METRICS MODIFY COLUMN "Facility Name"           SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_STRING_PII;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.READMISSION_METRICS MODIFY COLUMN "Number of Readmissions"  SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_CLINICAL_METRIC_VARCHAR;
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.READMISSION_METRICS MODIFY COLUMN "Excess Readmission Ratio" SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_CLINICAL_METRIC;

-- COST_ANALYTICS
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COST_ANALYTICS MODIFY COLUMN "Value" SET MASKING POLICY HEALTHCARE_DB.GOVERNANCE.MASK_FINANCIAL_VALUE;

-- Check all policies applied
-- SELECT *
-- FROM TABLE(HEALTHCARE_DB.INFORMATION_SCHEMA.POLICY_REFERENCES(
--     REF_ENTITY_NAME => 'HEALTHCARE_DB.RAW_SCHEMA.FACILITIES',
--     REF_ENTITY_DOMAIN => 'TABLE'
-- ));

----------------------------------------------------------------------
-- 1. ROW ACCESS POLICY
-- Restricts data visibility by state based on role-to-region mapping
----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS HEALTHCARE_DB.GOVERNANCE.STATE_ACCESS_MAPPING (
    ROLE_NAME     VARCHAR,
    ALLOWED_STATE VARCHAR,
    CONSTRAINT pk_state_access PRIMARY KEY (ROLE_NAME, ALLOWED_STATE)
);

INSERT INTO HEALTHCARE_DB.GOVERNANCE.STATE_ACCESS_MAPPING
    (ROLE_NAME, ALLOWED_STATE)
VALUES
    ('ACCOUNTADMIN',       'ALL'),
    ('ADMIN_ROLE',         'ALL'),
    ('DATA_ENGINEER_ROLE', 'ALL'),
    ('DATA_ANALYST_ROLE',  'ALL'),
    ('DATA_INGEST_ROLE',   'ALL'),
    ('REPORTING_ROLE',     'AL'),
    ('REPORTING_ROLE',     'CA'),
    ('REPORTING_ROLE',     'NY'),
    ('REPORTING_ROLE',     'TX'),
    ('REPORTING_ROLE',     'FL');

CREATE OR REPLACE ROW ACCESS POLICY HEALTHCARE_DB.GOVERNANCE.RAP_STATE_FILTER
AS (state_col VARCHAR)
RETURNS BOOLEAN ->
    EXISTS (
        SELECT 1
        FROM HEALTHCARE_DB.GOVERNANCE.STATE_ACCESS_MAPPING
        WHERE IS_ROLE_IN_SESSION(ROLE_NAME)
          AND (ALLOWED_STATE = state_col OR ALLOWED_STATE = 'ALL')
    );

-- APPLY ROW ACCESS POLICY
ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.FACILITIES
    ADD ROW ACCESS POLICY HEALTHCARE_DB.GOVERNANCE.RAP_STATE_FILTER ON ("State");

ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.PATIENT_SURVEY
    ADD ROW ACCESS POLICY HEALTHCARE_DB.GOVERNANCE.RAP_STATE_FILTER ON ("State");

ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.ENCOUNTERS
    ADD ROW ACCESS POLICY HEALTHCARE_DB.GOVERNANCE.RAP_STATE_FILTER ON ("State");

ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.COMPLICATIONS_AND_DEATHS_HOSPITAL
    ADD ROW ACCESS POLICY HEALTHCARE_DB.GOVERNANCE.RAP_STATE_FILTER ON ("State");

ALTER TABLE HEALTHCARE_DB.RAW_SCHEMA.READMISSION_METRICS
    ADD ROW ACCESS POLICY HEALTHCARE_DB.GOVERNANCE.RAP_STATE_FILTER ON ("State");